(()=>{"use strict";document.documentElement.classList.add("js-ready");
const PASS="333784",META="data/images.json",BRANCH="main",API="https://api.github.com",$=id=>document.getElementById(id);
const s={images:[],tab:"all",cat:"All",q:"",sort:"newest",viewer:null,busy:false};
function repo(){let h=location.hostname,p=location.pathname.split("/").filter(Boolean);return h.endsWith(".github.io")&&h.split(".")[0]&&p[0]?{owner:h.split(".")[0],repo:p[0]}:{owner:"",repo:""}}const R=repo();$("repoInfo").textContent=R.owner?R.owner+"/"+R.repo:"GitHub Pages repo detect नहीं हुआ";
function toast(x,t=3200){let e=$("toast");e.textContent=x;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),t)}
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function path(p){return p.split("/").map(encodeURIComponent).join("/")}
function url(x){return x.url||`https://raw.githubusercontent.com/${R.owner}/${R.repo}/${BRANCH}/${path(x.path)}`}
function api(p){return`${API}/repos/${encodeURIComponent(R.owner)}/${encodeURIComponent(R.repo)}/contents/${path(p)}`}
function heads(t){return{"Accept":"application/vnd.github+json","Authorization":"Bearer "+t,"X-GitHub-Api-Version":"2022-11-28"}}
async function aj(u,o={}){let r=await fetch(u,o),d=null;try{d=await r.json()}catch{}if(!r.ok)throw Error(d?.message||`${r.status} ${r.statusText}`);return d}
function dt(v){let d=new Date(v);return isNaN(d)?"Unknown date":new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function dk(v){let d=new Date(v);return isNaN(d)?"":`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
async function load(){ $("statusArea").textContent="Gallery data load हो रहा है…";try{let r=await fetch(`data/images.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw Error(`data/images.json ${r.status}`);let d=await r.json();if(!Array.isArray(d))throw Error("images.json array नहीं है");s.images=d.map((x,i)=>({id:x.id||x.path||i,name:x.name||(x.path||"").split("/").pop()||"Image",path:x.path||"",url:x.url||"",category:x.category||"Uncategorized",keywords:Array.isArray(x.keywords)?x.keywords:String(x.keywords||"").split(",").map(a=>a.trim()).filter(Boolean),uploadedAt:x.uploadedAt||x.date||""}));cats();render();$("statusArea").textContent=`${s.images.length} image${s.images.length===1?"":"s"} loaded`}catch(e){s.images=[];render();$("statusArea").textContent="Gallery data error: "+e.message;toast("data/images.json load नहीं हुआ।",5000)}}
function cats(){let c=[...new Set(s.images.map(x=>x.category).filter(Boolean))].sort();let b=$("categoryBar");b.innerHTML="";let a=document.createElement("button");a.className="chip "+(s.cat==="All"?"active":"");a.textContent=`All (${s.images.length})`;a.onclick=()=>{s.cat="All";render()};b.append(a);c.forEach(k=>{let z=document.createElement("button");z.className="chip "+(s.cat===k?"active":"");z.textContent=`${k} (${s.images.filter(x=>x.category===k).length})`;z.onclick=()=>{s.cat=k;render()};b.append(z)});$("categoryOptions").innerHTML=c.map(x=>`<option value="${esc(x)}">`).join("")}
function ok(x){if(s.cat!=="All"&&x.category!==s.cat)return false;let q=s.q.trim().toLowerCase();if(!q)return true;return[x.name,x.category,...x.keywords,dt(x.uploadedAt),dk(x.uploadedAt),x.uploadedAt].join(" ").toLowerCase().includes(q)}
function cmp(a,b){if(s.sort==="az")return a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:"base"});if(s.sort==="za")return b.name.localeCompare(a.name,undefined,{numeric:true,sensitivity:"base"});let A=Date.parse(a.uploadedAt)||0,B=Date.parse(b.uploadedAt)||0;return s.sort==="oldest"?A-B:B-A}
function render(){let arr=s.images.filter(ok).sort(cmp),g=$("gallery");g.innerHTML="";$("clearSearch").classList.toggle("hidden",!s.q);document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===s.tab));cats();if(s.tab==="activity"){arr.forEach(x=>{let e=document.createElement("article");e.className="card";e.style.padding="12px";e.innerHTML=`<b>Uploaded: ${esc(x.name)}</b><span class="date">${esc(dt(x.uploadedAt))} · ${esc(x.category)}</span>`;g.append(e)});$("emptyState").classList.toggle("hidden",!!arr.length);$("emptyTitle").textContent="No activity";$("emptyText").textContent="इस search/category में activity नहीं मिली।";return}if(!arr.length){$("emptyState").classList.remove("hidden");$("emptyTitle").textContent=s.images.length?"No matching images":"No images";$("emptyText").textContent=s.images.length?"Search/category/order बदलकर देखें।":"data/images.json में अभी कोई image नहीं है।";return}$("emptyState").classList.add("hidden");arr.forEach(x=>{let c=document.createElement("article");c.className="card";let im=document.createElement("img");im.src=url(x);im.alt=x.name;im.loading="lazy";im.onerror=()=>im.style.opacity=".35";im.onclick=()=>viewer(x);let b=document.createElement("div");b.className="card-body";b.innerHTML=`<span class="date">${esc(dt(x.uploadedAt))}</span>`;c.append(im,b);g.append(c)})}
function menu(open){$("menuPanel").classList.toggle("open",open);$("menuPanel").setAttribute("aria-hidden",String(!open));$("menuBackdrop").hidden=!open;if(!open&&!document.querySelector(".modal:not([hidden])"))document.body.style.overflow="";else if(open)document.body.style.overflow="hidden"}
function modal(id,on=true){$(id).hidden=!on;document.body.style.overflow=on?"hidden":""}
function viewer(x){s.viewer=x;$("viewerImage").src=url(x);$("viewerImage").alt=x.name;$("viewerName").textContent=x.name;$("viewerDate").textContent=dt(x.uploadedAt);$("downloadBtn").href=url(x);$("downloadBtn").download=x.name;$("originalBtn").href=url(x);modal("viewerModal",true)}
function closeViewer(){modal("viewerModal",false);s.viewer=null;$("viewerImage").src=""}
function b64(file){return new Promise((res,rej)=>{let f=new FileReader();f.onload=()=>res(String(f.result).split(",")[1]);f.onerror=rej;f.readAsDataURL(file)})}
async function meta(t){return aj(api(META),{headers:heads(t)})}
async function putMeta(t,sha,d,msg){let raw=unescape(encodeURIComponent(JSON.stringify(d,null,2)+"\n")),c=btoa(raw);return aj(api(META),{method:"PUT",headers:{...heads(t),"Content-Type":"application/json"},body:JSON.stringify({message:msg,content:c,branch:BRANCH,sha})})}
async function putFile(t,p,c,msg){return aj(api(p),{method:"PUT",headers:{...heads(t),"Content-Type":"application/json"},body:JSON.stringify({message:msg,content:c,branch:BRANCH})})}
async function delFile(t,p,sha,msg){return aj(api(p),{method:"DELETE",headers:{...heads(t),"Content-Type":"application/json"},body:JSON.stringify({message:msg,sha,branch:BRANCH})})}

$("menuBtn").onclick=()=>menu(true);$("menuClose").onclick=()=>menu(false);$("menuBackdrop").onclick=()=>menu(false);
$("openUpload").onclick=()=>{menu(false);modal("uploadModal",true)};$("openForce").onclick=()=>{menu(false);forceList();modal("forceModal",true)};
$("normalMode").onclick=()=>{localStorage.setItem("mode","normal");document.body.classList.remove("dark");menu(false)};$("darkMode").onclick=()=>{localStorage.setItem("mode","dark");document.body.classList.add("dark");menu(false)};
document.querySelectorAll(".modal-close").forEach(b=>b.onclick=()=>modal(b.dataset.close,false));
$("viewerClose").onclick=closeViewer;$("viewerModal").onclick=e=>{if(e.target===$("viewerModal"))closeViewer()};
$("viewerForce").onclick=()=>{if(!s.viewer)return;let id=s.viewer.id;closeViewer();forceList(id);modal("forceModal",true)};
document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;if(!$("viewerModal").hidden)closeViewer();else if(!$("uploadModal").hidden)modal("uploadModal",false);else if(!$("forceModal").hidden)modal("forceModal",false);else menu(false)});
$("searchInput").oninput=e=>{s.q=e.target.value;render()};$("clearSearch").onclick=()=>{$("searchInput").value="";s.q="";render()};
$("sortSelect").onchange=e=>{s.sort=e.target.value;render()};document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{s.tab=b.dataset.tab;render()});
$("uploadFiles").onchange=()=>{$("uploadPreview").innerHTML="";[...$("uploadFiles").files].slice(0,15).forEach(f=>{let i=document.createElement("img");i.src=URL.createObjectURL(f);$("uploadPreview").append(i)})};

$("uploadForm").onsubmit=async e=>{e.preventDefault();if(s.busy)return;let pw=$("uploadPassword").value,t=$("uploadToken").value.trim(),cat=$("uploadCategory").value.trim()||"Uncategorized",keys=$("uploadKeywords").value.split(",").map(x=>x.trim()).filter(Boolean),files=[...$("uploadFiles").files];if(pw!==PASS)return toast("Password गलत है।");if(!t)return toast("GitHub token डालें।");if(!files.length)return toast("Images चुनें।");if(!R.owner)return toast("GitHub Pages repository detect नहीं हुआ।");s.busy=true;let p=$("uploadProgress");p.hidden=false;try{let m=await meta(t),old=JSON.parse(decodeURIComponent(escape(atob(m.content.replace(/\\n/g,""))))),newItems=[];for(let i=0;i<files.length;i++){let f=files[i];if(!f.type.startsWith("image/"))throw Error(f.name+" image नहीं है");if(f.size>20*1024*1024)throw Error(f.name+" 20 MB से बड़ी है");let name=f.name.replace(/[^\w.\- ()]+/g,"_"),pth=`images/${Date.now()}-${i}-${name}`;p.textContent=`Uploading ${i+1}/${files.length}: ${f.name}`;await putFile(t,pth,await b64(f),`Upload image: ${name}`);let x={id:pth,name,path:pth,category:cat,keywords:keys,uploadedAt:new Date().toISOString()};newItems.push(x);s.images.unshift(x);render()}await putMeta(t,m.sha,[...newItems,...old],"Update image library metadata");toast(`${newItems.length} image upload हो गईं।`);$("uploadForm").reset();$("uploadPreview").innerHTML="";modal("uploadModal",false)}catch(err){p.textContent="Upload error: "+err.message;toast("Upload failed: "+err.message,6000)}finally{s.busy=false}};

function forceList(pre=""){let box=$("forceList");box.innerHTML="";if(!s.images.length){box.innerHTML="<div style='padding:16px;color:#6b7280'>कोई image नहीं है।</div>";return}s.images.slice().sort(cmp).forEach(x=>{let r=document.createElement("div");r.className="force-row";r.innerHTML=`<input type="checkbox" value="${esc(x.id)}" ${x.id===pre?"checked":""}><img src="${esc(url(x))}"><span>${esc(x.name)}<br>${esc(dt(x.uploadedAt))}</span>`;box.append(r)})}
$("selectAll").onclick=()=>document.querySelectorAll("#forceList input").forEach(x=>x.checked=true);$("selectNone").onclick=()=>document.querySelectorAll("#forceList input").forEach(x=>x.checked=false);
$("forceForm").onsubmit=async e=>{e.preventDefault();if(s.busy)return;let pw=$("forcePassword").value,t=$("forceToken").value.trim(),ids=[...document.querySelectorAll("#forceList input:checked")].map(x=>x.value);if(pw!==PASS)return toast("Password गलत है।");if(!t)return toast("GitHub token डालें।");if(!ids.length)return toast("Images select करें।");if(!confirm(`क्या ${ids.length} image permanently Force Delete करना है?`))return;s.busy=true;let p=$("forceProgress");p.hidden=false;try{let m=await meta(t),old=JSON.parse(decodeURIComponent(escape(atob(m.content.replace(/\\n/g,""))))),removed=0;for(let id of ids){let x=s.images.find(z=>z.id===id);if(!x)continue;p.textContent=`Deleting: ${x.name}`;let info=await aj(api(x.path),{headers:heads(t)});await delFile(t,x.path,info.sha,"Force delete image: "+x.name);s.images=s.images.filter(z=>z.id!==id);old=old.filter(z=>z.id!==id&&z.path!==x.path);removed++;render();forceList()}await putMeta(t,m.sha,old,"Update image library metadata after Force delete");toast(`${removed} image Force Delete हो गईं।`);$("forceForm").reset();modal("forceModal",false)}catch(err){p.textContent="Force error: "+err.message;render();toast("Force failed: "+err.message,6000)}finally{s.busy=false}};
if(localStorage.getItem("mode")==="dark")document.body.classList.add("dark");load();
})();